<a href="https://colab.research.google.com/github/mandalsudipta/deep_learning/blob/main/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
torch.__version__

'2.4.0+cu121'

In [ ]:
import torch
scaler = torch.tensor(3)
scaler, scaler.ndim, scaler.item()

(tensor(3), 0, 3)

In [ ]:
vector=torch.tensor([1,2])
vector, vector.ndim, vector.shape

(tensor([1, 2]), 1, torch.Size([2]))

In [ ]:
#Matrix
matrix=torch.tensor([[1,2],[3,4]])
matrix, matrix.ndim, matrix.shape,matrix[0],matrix[1]

(tensor([[1, 2],
         [3, 4]]),
 2,
 torch.Size([2, 2]),
 tensor([1, 2]),
 tensor([3, 4]))

In [9]:
#Tensor
TENSOR=torch.tensor([[1,2,3]])
print(f"Tensor : {TENSOR}")
print(f"Dimension : {TENSOR.ndim}")
print(f"Shape : {TENSOR.shape}")
print(f"Element : {TENSOR[0]}")

print(f"Element : {TENSOR[0][0]}")
print(f"Element : {TENSOR[0][1]}")
print(f"Element : {TENSOR[0][2]}")

Tensor : tensor([[1, 2, 3]])
Dimension : 2
Shape : torch.Size([1, 3])
Element : tensor([1, 2, 3])
Element : 1
Element : 2
Element : 3


In [18]:
#Tensor
TENSOR=torch.tensor([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(f"Tensor : {TENSOR}")
print(f"Dimension : {TENSOR.ndim}")
print(f"Shape : {TENSOR.shape}")
print(f"Element 0th : {TENSOR[0]}")
print(f"Element 1th: {TENSOR[1]}")
print(f"Element 00th : {TENSOR[0][0]}")
print(f"Element 01th: {TENSOR[0][1]}")
print(f"Element 10th: {TENSOR[1][0]}")
print(f"Element 11th: {TENSOR[1][1]}")

Tensor : tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])
Dimension : 3
Shape : torch.Size([2, 2, 3])
Element 0th : tensor([[1, 2, 3],
        [4, 5, 6]])
Element 1th: tensor([[ 7,  8,  9],
        [10, 11, 12]])
Element 00th : tensor([1, 2, 3])
Element 01th: tensor([4, 5, 6])
Element 10th: tensor([7, 8, 9])
Element 11th: tensor([10, 11, 12])


In [3]:
#Tensor
TENSOR=torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
TENSOR, TENSOR.ndim, TENSOR.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 3,
 torch.Size([1, 3, 3]))

In [ ]:
#Tensor
TENSOR=torch.tensor([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])
TENSOR, TENSOR.ndim, TENSOR.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]],
 
         [[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 3,
 torch.Size([2, 3, 3]))

In [19]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6]])

In [27]:
#Random tensors
random_tensor=torch.rand(1,1,3,4)
random_tensor, random_tensor.ndim

(tensor([[[[0.4092, 0.6768, 0.3349, 0.9035],
           [0.4944, 0.4070, 0.1732, 0.3757],
           [0.5269, 0.9784, 0.7134, 0.9728]]]]),
 4)

In [29]:
random_tensor=torch.rand(2,3,3,4)
random_tensor, random_tensor.ndim

(tensor([[[[0.7663, 0.9049, 0.1163, 0.6578],
           [0.1661, 0.7486, 0.3235, 0.6276],
           [0.2453, 0.2602, 0.9380, 0.1806]],
 
          [[0.4085, 0.0132, 0.8182, 0.6582],
           [0.6468, 0.5449, 0.6753, 0.3743],
           [0.3089, 0.7815, 0.0750, 0.3458]],
 
          [[0.2341, 0.0923, 0.7100, 0.9165],
           [0.4482, 0.4518, 0.9329, 0.1933],
           [0.9818, 0.6350, 0.9113, 0.4275]]],
 
 
         [[[0.5645, 0.2946, 0.2947, 0.2681],
           [0.1016, 0.9211, 0.3624, 0.6637],
           [0.1842, 0.3308, 0.0134, 0.9004]],
 
          [[0.1860, 0.5390, 0.1407, 0.8606],
           [0.6980, 0.3429, 0.4733, 0.0709],
           [0.2677, 0.9774, 0.3701, 0.6720]],
 
          [[0.4830, 0.8262, 0.5845, 0.5706],
           [0.8139, 0.1443, 0.1878, 0.3021],
           [0.2687, 0.6138, 0.4044, 0.4096]]]]),
 4)

In [33]:
#Creating a random tensor with similar shape of an image tensor
image_tensor=torch.rand(size=(3,224,224))
image_tensor,image_tensor.shape, image_tensor.ndim

(tensor([[[0.1185, 0.0498, 0.4543,  ..., 0.0817, 0.9226, 0.8809],
          [0.9089, 0.6784, 0.2458,  ..., 0.0950, 0.7098, 0.1754],
          [0.7564, 0.5009, 0.7120,  ..., 0.7956, 0.2044, 0.7308],
          ...,
          [0.1462, 0.9186, 0.6305,  ..., 0.8619, 0.8311, 0.9868],
          [0.4158, 0.5188, 0.7804,  ..., 0.8560, 0.6583, 0.0277],
          [0.9377, 0.7517, 0.3964,  ..., 0.5894, 0.9585, 0.3315]],
 
         [[0.1400, 0.1050, 0.3729,  ..., 0.7491, 0.9119, 0.3719],
          [0.6121, 0.6930, 0.4529,  ..., 0.3929, 0.7264, 0.8781],
          [0.5077, 0.1259, 0.9631,  ..., 0.9163, 0.0234, 0.3922],
          ...,
          [0.3684, 0.1422, 0.5174,  ..., 0.5409, 0.5634, 0.7254],
          [0.0796, 0.0334, 0.9905,  ..., 0.3946, 0.7267, 0.9278],
          [0.4267, 0.0600, 0.4665,  ..., 0.4172, 0.5476, 0.9358]],
 
         [[0.8047, 0.5250, 0.7985,  ..., 0.7840, 0.1101, 0.9524],
          [0.3925, 0.1353, 0.8274,  ..., 0.9399, 0.4063, 0.2224],
          [0.6150, 0.2935, 0.3677,  ...,

In [34]:
#random tensor with all zeros
torch_zeros=torch.zeros(size=(3,4))
torch_zeros, torch_zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [35]:
#random tensor with all ones
torch_ones=torch.ones(size=(3,4))
torch_ones, torch_ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [37]:
torch_zeros*torch_ones

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [39]:
#arange method
torch_range=torch.arange(0,10)
torch_range

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
#arange method
torch_range_step=torch.arange(start=0,end=10,step=2)
torch_range

tensor([0, 2, 4, 6, 8])

In [40]:
#creating tensors like
torch_zeros_like=torch.zeros_like(input=torch_range)
torch_zeros_like

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [42]:
#creating tensors like
torch_ones_like=torch.ones_like(torch_range) #input keyword is optional
torch_ones_like

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [45]:
#creating tensors like
torch_random_like=torch.rand_like(input=torch_range.float()) # Cast torch_range to float
torch_random_like

tensor([0.2745, 0.1981, 0.4006, 0.7291, 0.8775, 0.4452, 0.4648, 0.3489, 0.3994,
        0.5366])

# **Tensor Data Types**

In [46]:
#Tensor float32 data types
float_32_tensor=torch.tensor([1.0,2.0,3.0],dtype=None)
float_32_tensor, float_32_tensor.dtype

(tensor([1., 2., 3.]), torch.float32)

In [48]:
#Tensor float32 data types
float_32_tensor=torch.tensor([1.0,2.0,3.0],dtype=torch.float16)
float_32_tensor, float_32_tensor.dtype


(tensor([1., 2., 3.], dtype=torch.float16), torch.float16)

In [49]:
#Tensor float16 data types
float_32_tensor=torch.tensor([1.0,2.0,3.0],
                             dtype=torch.float16, #what datatype the tensor
                             device=None, #what device the tensor is running
                             requires_grad=False) #Whether to track the gradients of the tensor operations
float_32_tensor, float_32_tensor.dtype

(tensor([1., 2., 3.], dtype=torch.float16), torch.float16)

Three types of tensor errors can be found in deep learning and pytorch
1. The tensors not right datatype
2. The tensor not right shape
3. tensors not right device


In [54]:
#data type change
tensor_float32=torch.tensor([1.0,2.0,3.0],
                             dtype=None, #what datatype the tensor
                             device=None, #what device the tensor is running
                             requires_grad=False)
tensor_float16=tensor_float32.type(torch.float16)
tensor_float16, tensor_float16.dtype

(tensor([1., 2., 3.], dtype=torch.float16), torch.float16)