In [1]:
import torch
torch.__version__

'2.4.0+cu121'

In [ ]:
import torch
scaler = torch.tensor(3)
scaler, scaler.ndim, scaler.item()

(tensor(3), 0, 3)

In [ ]:
vector=torch.tensor([1,2])
vector, vector.ndim, vector.shape

(tensor([1, 2]), 1, torch.Size([2]))

In [ ]:
#Matrix
matrix=torch.tensor([[1,2],[3,4]])
matrix, matrix.ndim, matrix.shape,matrix[0],matrix[1]

(tensor([[1, 2],
         [3, 4]]),
 2,
 torch.Size([2, 2]),
 tensor([1, 2]),
 tensor([3, 4]))

In [ ]:
#Tensor
TENSOR=torch.tensor([[1,2,3]])
print(f"Tensor : {TENSOR}")
print(f"Dimension : {TENSOR.ndim}")
print(f"Shape : {TENSOR.shape}")
print(f"Element : {TENSOR[0]}")

print(f"Element : {TENSOR[0][0]}")
print(f"Element : {TENSOR[0][1]}")
print(f"Element : {TENSOR[0][2]}")

Tensor : tensor([[1, 2, 3]])
Dimension : 2
Shape : torch.Size([1, 3])
Element : tensor([1, 2, 3])
Element : 1
Element : 2
Element : 3


In [ ]:
#Tensor
TENSOR=torch.tensor([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(f"Tensor : {TENSOR}")
print(f"Dimension : {TENSOR.ndim}")
print(f"Shape : {TENSOR.shape}")
print(f"Element 0th : {TENSOR[0]}")
print(f"Element 1th: {TENSOR[1]}")
print(f"Element 00th : {TENSOR[0][0]}")
print(f"Element 01th: {TENSOR[0][1]}")
print(f"Element 10th: {TENSOR[1][0]}")
print(f"Element 11th: {TENSOR[1][1]}")

Tensor : tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])
Dimension : 3
Shape : torch.Size([2, 2, 3])
Element 0th : tensor([[1, 2, 3],
        [4, 5, 6]])
Element 1th: tensor([[ 7,  8,  9],
        [10, 11, 12]])
Element 00th : tensor([1, 2, 3])
Element 01th: tensor([4, 5, 6])
Element 10th: tensor([7, 8, 9])
Element 11th: tensor([10, 11, 12])


In [ ]:
#Tensor
TENSOR=torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
TENSOR, TENSOR.ndim, TENSOR.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 3,
 torch.Size([1, 3, 3]))

In [ ]:
#Tensor
TENSOR=torch.tensor([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])
TENSOR, TENSOR.ndim, TENSOR.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]],
 
         [[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 3,
 torch.Size([2, 3, 3]))

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
#Random tensors
random_tensor=torch.rand(1,1,3,4)
random_tensor, random_tensor.ndim

(tensor([[[[0.4092, 0.6768, 0.3349, 0.9035],
           [0.4944, 0.4070, 0.1732, 0.3757],
           [0.5269, 0.9784, 0.7134, 0.9728]]]]),
 4)

In [ ]:
random_tensor=torch.rand(2,3,3,4)
random_tensor, random_tensor.ndim

(tensor([[[[0.7663, 0.9049, 0.1163, 0.6578],
           [0.1661, 0.7486, 0.3235, 0.6276],
           [0.2453, 0.2602, 0.9380, 0.1806]],
 
          [[0.4085, 0.0132, 0.8182, 0.6582],
           [0.6468, 0.5449, 0.6753, 0.3743],
           [0.3089, 0.7815, 0.0750, 0.3458]],
 
          [[0.2341, 0.0923, 0.7100, 0.9165],
           [0.4482, 0.4518, 0.9329, 0.1933],
           [0.9818, 0.6350, 0.9113, 0.4275]]],
 
 
         [[[0.5645, 0.2946, 0.2947, 0.2681],
           [0.1016, 0.9211, 0.3624, 0.6637],
           [0.1842, 0.3308, 0.0134, 0.9004]],
 
          [[0.1860, 0.5390, 0.1407, 0.8606],
           [0.6980, 0.3429, 0.4733, 0.0709],
           [0.2677, 0.9774, 0.3701, 0.6720]],
 
          [[0.4830, 0.8262, 0.5845, 0.5706],
           [0.8139, 0.1443, 0.1878, 0.3021],
           [0.2687, 0.6138, 0.4044, 0.4096]]]]),
 4)

In [ ]:
#Creating a random tensor with similar shape of an image tensor
image_tensor=torch.rand(size=(3,224,224))
image_tensor,image_tensor.shape, image_tensor.ndim

(tensor([[[0.1185, 0.0498, 0.4543,  ..., 0.0817, 0.9226, 0.8809],
          [0.9089, 0.6784, 0.2458,  ..., 0.0950, 0.7098, 0.1754],
          [0.7564, 0.5009, 0.7120,  ..., 0.7956, 0.2044, 0.7308],
          ...,
          [0.1462, 0.9186, 0.6305,  ..., 0.8619, 0.8311, 0.9868],
          [0.4158, 0.5188, 0.7804,  ..., 0.8560, 0.6583, 0.0277],
          [0.9377, 0.7517, 0.3964,  ..., 0.5894, 0.9585, 0.3315]],
 
         [[0.1400, 0.1050, 0.3729,  ..., 0.7491, 0.9119, 0.3719],
          [0.6121, 0.6930, 0.4529,  ..., 0.3929, 0.7264, 0.8781],
          [0.5077, 0.1259, 0.9631,  ..., 0.9163, 0.0234, 0.3922],
          ...,
          [0.3684, 0.1422, 0.5174,  ..., 0.5409, 0.5634, 0.7254],
          [0.0796, 0.0334, 0.9905,  ..., 0.3946, 0.7267, 0.9278],
          [0.4267, 0.0600, 0.4665,  ..., 0.4172, 0.5476, 0.9358]],
 
         [[0.8047, 0.5250, 0.7985,  ..., 0.7840, 0.1101, 0.9524],
          [0.3925, 0.1353, 0.8274,  ..., 0.9399, 0.4063, 0.2224],
          [0.6150, 0.2935, 0.3677,  ...,

In [ ]:
#random tensor with all zeros
torch_zeros=torch.zeros(size=(3,4))
torch_zeros, torch_zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [ ]:
#random tensor with all ones
torch_ones=torch.ones(size=(3,4))
torch_ones, torch_ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [ ]:
torch_zeros*torch_ones

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
#arange method
torch_range=torch.arange(0,10)
torch_range

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#arange method
torch_range_step=torch.arange(start=0,end=10,step=2)
torch_range

tensor([0, 2, 4, 6, 8])

In [ ]:
#creating tensors like
torch_zeros_like=torch.zeros_like(input=torch_range)
torch_zeros_like

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
#creating tensors like
torch_ones_like=torch.ones_like(torch_range) #input keyword is optional
torch_ones_like

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [ ]:
#creating tensors like
torch_random_like=torch.rand_like(input=torch_range.float()) # Cast torch_range to float
torch_random_like

tensor([0.2745, 0.1981, 0.4006, 0.7291, 0.8775, 0.4452, 0.4648, 0.3489, 0.3994,
        0.5366])

# **Tensor Data Types**

In [ ]:
#Tensor float32 data types
float_32_tensor=torch.tensor([1.0,2.0,3.0],dtype=None)
float_32_tensor, float_32_tensor.dtype

(tensor([1., 2., 3.]), torch.float32)

In [ ]:
#Tensor float32 data types
float_32_tensor=torch.tensor([1.0,2.0,3.0],dtype=torch.float16)
float_32_tensor, float_32_tensor.dtype


(tensor([1., 2., 3.], dtype=torch.float16), torch.float16)

In [ ]:
#Tensor float16 data types
float_32_tensor=torch.tensor([1.0,2.0,3.0],
                             dtype=torch.float16, #what datatype the tensor
                             device=None, #what device the tensor is running
                             requires_grad=False) #Whether to track the gradients of the tensor operations
float_32_tensor, float_32_tensor.dtype

(tensor([1., 2., 3.], dtype=torch.float16), torch.float16)

Three types of tensor errors can be found in deep learning and pytorch
1. The tensors not right datatype
2. The tensor not right shape
3. tensors not right device


In [ ]:
#data type change
tensor_float32=torch.tensor([1.0,2.0,3.0],
                             dtype=None, #what datatype the tensor
                             device=None, #what device the tensor is running
                             requires_grad=False)
tensor_float16=tensor_float32.type(torch.float16)
tensor_float16, tensor_float16.dtype

(tensor([1., 2., 3.], dtype=torch.float16), torch.float16)

Tensors Arith Matic Operations
1. Addition
2. Subtraction
3. Multiplication
4. Division
5. Matrix Multiplication


In [7]:
import torch
tensor=torch.tensor([1,2,3])
tensor+10,tensor-10,tensor*10,tensor/10

(tensor([11, 12, 13]),
 tensor([-9, -8, -7]),
 tensor([10, 20, 30]),
 tensor([0.1000, 0.2000, 0.3000]))

Using in-built function

In [9]:
import torch
tensor.add(10),tensor.sub(10),tensor.mul(10),tensor.div(10) #tensor dot function can be used

(tensor([11, 12, 13]),
 tensor([-9, -8, -7]),
 tensor([10, 20, 30]),
 tensor([0.1000, 0.2000, 0.3000]))

In [10]:
import torch
torch.mul(tensor,10),torch.add(tensor,10),torch.sub(tensor,10),torch.div(tensor,10) #Alternatively torch dot function also can be used

(tensor([10, 20, 30]),
 tensor([11, 12, 13]),
 tensor([-9, -8, -7]),
 tensor([0.1000, 0.2000, 0.3000]))

Matrix Multiplication
1. Element wise
2. using matmul method matrix multiplication(dot product)


In [19]:
%%time
value=0
for i in range (len(tensor)):
  value += tensor[i]*tensor[i]
value

CPU times: user 0 ns, sys: 1.76 ms, total: 1.76 ms
Wall time: 1.53 ms


tensor(14)

In [20]:
%%time
torch.matmul(tensor,tensor) #using matmul method

CPU times: user 496 µs, sys: 0 ns, total: 496 µs
Wall time: 503 µs


tensor(14)

In [26]:
#Instead of matmul we can use @ also
tensor @ tensor

tensor(14)

In [24]:
#During matrix Multiplication the inner value must match for multiplication eligibility and the result will match the dimension of the outer value for example
# (2X3) can be multiplied by (3x2) and result matrix dimension will be (2x2)
tensor1=torch.tensor([[1,2,3],[4,5,6]])
tensor2=torch.tensor([[5,6],[7,8],[9,10]])
torch.matmul(tensor1,tensor2)

tensor([[ 46,  52],
        [109, 124]])

In [25]:
# So (2X3) can be multiplied by (3x3) and result matrix dimension will be (2x3)
tensor1=torch.tensor([[1,2,3],[4,5,6]])
tensor2=torch.tensor([[5,6,7],[8,9,10],[11,12,13]])
torch.matmul(tensor1,tensor2)

tensor([[ 54,  60,  66],
        [126, 141, 156]])

In [28]:
#To handle the tensor shape issue we can take the transpose of the matrix
tensor1
tensor1_transpose=tensor1.T
tensor1_transpose

tensor([[1, 4],
        [2, 5],
        [3, 6]])

Tensor Aggregation
min, max, mean and sum

In [37]:
#tensor aggregation examples
x=(torch.arange(0,100,10))
x, x.dtype,x.min(), x.max(), (x.type(torch.float32)).mean(), x.sum() #Since mean() always return a float data type

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]),
 torch.int64,
 tensor(0),
 tensor(90),
 tensor(45.),
 tensor(450))

Finding the Positional min, max of the tensor

In [38]:
#the method argmin() and argmax() are used to get the position of the min and max value of a tensor
x=torch.arange(1,10)
x, x.argmin(), x.argmax()

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), tensor(0), tensor(8))

In [41]:
xy=torch.rand(3,3)
xy, xy.argmin(), xy.argmax()


(tensor([[0.0811, 0.3437, 0.3567],
         [0.0930, 0.0226, 0.4762],
         [0.8093, 0.8388, 0.3028]]),
 tensor(4),
 tensor(7))

**Reshaping, viewing,squeezing, unsqueezing and Stacking tensors**

**reshaping :** changing the shape of a original tensor

**viewing :** changing the view of a given tenso. View always refers the original memory of the tensor

**stacking:** placing tensors on top of other tensor(vstack) or side bi side(hstack). A method of tensor concatenation

**squeeze:** removes all '1' dimension from a tensor

**unsqueeze :** adds all '1' dimension to a target tensor

**Permute :** Returns a view of the input with dimension permuted(swapped)



In [46]:
#reshaping a tensor
x=torch.arange(1,10)
x_reshaped=x.reshape(1,9)
x_another_reshaped=x.reshape(3,3)
x, x.shape,x_reshaped, x_reshaped.shape,x_another_reshaped, x_another_reshaped.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 torch.Size([9]),
 tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]),
 torch.Size([1, 9]),
 tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 torch.Size([3, 3]))

In [47]:
#view of a tensor
x=torch.arange(1,10)
z=x.view(1,9)
z, z.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [48]:
#changing z will chnage the value of x because the view of a tensor shares the same memory
z[:,0]=5
z,x


(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]), tensor([5, 2, 3, 4, 5, 6, 7, 8, 9]))

In [53]:
#stacking of tensors
new_tensors=torch.arange(1,10)
new_tensors_stacked=torch.stack([new_tensors,new_tensors,new_tensors],dim=0)
new_tensors_stacked_1=torch.stack([new_tensors,new_tensors,new_tensors],dim=1)
new_tensors,new_tensors_stacked, new_tensors_stacked_1

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9],
         [1, 2, 3, 4, 5, 6, 7, 8, 9],
         [1, 2, 3, 4, 5, 6, 7, 8, 9]]),
 tensor([[1, 1, 1],
         [2, 2, 2],
         [3, 3, 3],
         [4, 4, 4],
         [5, 5, 5],
         [6, 6, 6],
         [7, 7, 7],
         [8, 8, 8],
         [9, 9, 9]]))

In [60]:
#Squezee and Unsquezee
x=torch.arange(1,10)
x_reshaped=x.reshape(1,9)
x_squeezed=x_reshaped.squeeze()

x,x_reshaped, x.shape,x_reshaped.shape, x.ndim,x_reshaped.ndim,x_squeezed

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]),
 torch.Size([9]),
 torch.Size([1, 9]),
 1,
 2,
 tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [62]:
#Permute
x=torch.rand(size=(224,224,3))
x_permuted=x.permute(2,0,1) #shifts the axis 0->1, 1->2, 2->0
x.shape, x_permuted.shape

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

In [64]:
#numpy array to tensor
import torch
import numpy as np
array=np.arange(1.0,8.0)
tensor=torch.from_numpy(array)
tensor_to_numpy=tensor.numpy()
array, tensor,tensor_to_numpy


(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64),
 array([1., 2., 3., 4., 5., 6., 7.]))

In [1]:
#Reproducibilty trying to make random out of random
import torch
RANDOM_SEED=42
torch.manual_seed(RANDOM_SEED)
tensor_A=torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
tensor_B=torch.rand(3,4)
print(tensor_A)
print(tensor_B)
print(tensor_A==tensor_B)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
